### ISSUE TITLE
Is there any pre-trained weight available?

### ISSUE THREAD

**Issue by personwhofloat** [GXYM/DRRG#1]
As the question, is there any weight file available for evaluating?

**Comment by dy1998** [comment]
It seems that he uses textsnake to train 100 epochs. Maybe you can take a look at textsnake.

**Comment by tson1997** [comment]
> It seems that he uses textsnake to train 100 epochs. Maybe you can take a look at textsnake.

Is it true? I haven't seen him mention it in the paper

**Comment by dy1998** [comment]
> > It seems that he uses textsnake to train 100 epochs. Maybe you can take a look at textsnake.
> 
> Thank you. Is it true? I haven't seen him mention it in the paper
You can take a look at https://github.com/princewang1994/TextSnake.pytorch. I found that some code is similar with DRPG.

**Comment by GXYM** [comment]
I'm sorry, there are some mistakes in the training script that caused misunderstanding. This is mainly because our code inherits from "textsnake", so there is "textsnake" in the name of our previously saved model. In the open source code, "textsnake" has been changed to "textgraph" to avoid people thinking that our method is an improved version of textsnake. In fact, there is a big difference between the two. However, there are still some "textsnake" that have not been modified. We will keep it updated. 

we use the code of textsnake, so there are some "textsnake“'  in code which We  haven't changed it. But that doesn't mean you can use the pretrain model of textsnake. you can run the script "tool/train_MLT2017.sh" and "tool/train_SynText.sh" to get the pretrain model.

**Comment by Joneo** [comment]
Do you have the download addresses of these two data sets？The data set I downloaded from the Internet doesn't work

**Comment by Joneo** [comment]
MLT2017 and SynText
